version: '3.8'
services: 

  web:
    container_name: 'thunes_sample_frontend'
    build: ./
    ports: 
    - 80:80
    depends_on: 
    - server

  server:
    environment:
    # - THUNES_APIKEY=Can set API key here
    # - THUNES_APISECRET=Can set API secret here
    - GIN_MODE=release
    container_name: 'thunes_sample_backend'
    image: fghpdf/thunes_sample_backend
    expose: 
    - 8080